build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest

packages:
  - python3
  - py3-pip
  - bash
  - curl

pip_packages:
  - requests
