name: "Hetzner IP Updater"
version: "1.0.6"
slug: hetzner_ip_updater
description: "Updates your public IP address on Hetzner DNS"
startup: "once"
boot: "manual"
host_network: true
init: false
data: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  hetzner_token: "YOUR_HETZNER_API_TOKEN"
  dns_zone: "example.com"
  dns_record_name: "home.example.com"
schema:
  hetzner_token: str
  dns_zone: str
  dns_record_name: str
